# Generated by Django 6.0.1 on 2026-01-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RERARegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('pending', 'Pending'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('registration_number', models.CharField(max_length=120)),
                ('valid_until', models.DateField()),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rera_registration', to='projects.project')),
            ],
            options={
                'ordering': ['valid_until'],
            },
        ),
        migrations.CreateModel(
            name='ComplianceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('compliant', 'Compliant'), ('pending', 'Pending'), ('non_compliant', 'Non-Compliant')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_items', to='projects.project')),
            ],
            options={
                'ordering': ['due_date'],
                'indexes': [models.Index(fields=['project', 'status'], name='compliance__project_e4ec79_idx')],
            },
        ),
        migrations.CreateModel(
            name='LegalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_id', models.CharField(max_length=60)),
                ('case_type', models.CharField(max_length=60)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=30)),
                ('filing_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legal_cases', to='projects.project')),
            ],
            options={
                'ordering': ['-filing_date'],
                'indexes': [models.Index(fields=['project', 'status'], name='compliance__project_c5c697_idx')],
                'unique_together': {('project', 'case_id')},
            },
        ),
    ]
