# Generated by Django 6.0.1 on 2026-01-27 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('project_code', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('delayed', 'Delayed'), ('stalled', 'Stalled'), ('completed', 'Completed')], default='on_track', max_length=20)),
                ('planned_start_date', models.DateField(blank=True, null=True)),
                ('actual_start_date', models.DateField(blank=True, null=True)),
                ('planned_completion_date', models.DateField(blank=True, null=True)),
                ('expected_completion_date', models.DateField(blank=True, null=True)),
                ('actual_completion_date', models.DateField(blank=True, null=True)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('rera_registration_number', models.CharField(blank=True, max_length=120)),
                ('rera_valid_until', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField(default=0)),
                ('tower', models.CharField(blank=True, max_length=50)),
                ('carpet_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('built_up_area', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('final_price', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('status', models.CharField(choices=[('available', 'Available'), ('blocked', 'Blocked'), ('booked', 'Booked'), ('sold', 'Sold')], default='available', max_length=20)),
                ('listed_date', models.DateField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='projects.project')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='core.unittype')),
            ],
            options={
                'ordering': ['project', 'tower', 'floor', 'unit_number'],
            },
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'status'], name='projects_pr_organiz_8941e0_idx'),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['organization', 'location'], name='projects_pr_organiz_2570c9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('organization', 'project_code')},
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['project', 'status'], name='projects_un_project_1cf609_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('project', 'unit_number')},
        ),
    ]
