# Generated by Django 6.0.1 on 2026-01-27 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendors', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(max_length=100)),
                ('bill_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to='projects.project')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='finance.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('paid_on', models.DateField()),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='finance.vendorbill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CashFlowEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flow_type', models.CharField(choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('category', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_entries', to='core.organization')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cashflow_entries', to='projects.project')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['organization', 'date'], name='finance_cas_organiz_463fb0_idx'), models.Index(fields=['project', 'date'], name='finance_cas_project_1925ea_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashFlowForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('projected_inflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('projected_outflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('net_cashflow', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('cumulative', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('confidence', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('key_risks', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cashflow_forecasts', to='core.organization')),
            ],
            options={
                'ordering': ['year', 'month'],
                'unique_together': {('organization', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['project', 'due_date'], name='finance_ven_project_926dc7_idx'),
        ),
        migrations.AddIndex(
            model_name='vendorbill',
            index=models.Index(fields=['status'], name='finance_ven_status_536493_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vendorbill',
            unique_together={('vendor', 'bill_no')},
        ),
    ]
