# Generated by Django 6.0.1 on 2026-01-27 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeyHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('highlight_date', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_highlights', to='core.organization')),
            ],
            options={
                'ordering': ['-highlight_date'],
                'indexes': [models.Index(fields=['organization', 'highlight_date'], name='governance__organiz_c20e2e_idx')],
            },
        ),
        migrations.CreateModel(
            name='QuarterlyPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('quarter', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('booked', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realized', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quarterly_performance', to='core.organization')),
            ],
            options={
                'ordering': ['-year', '-quarter'],
                'unique_together': {('organization', 'year', 'quarter')},
            },
        ),
        migrations.CreateModel(
            name='RevenueTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('projected', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('realized', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revenue_timeline', to='core.organization')),
            ],
            options={
                'ordering': ['year'],
                'unique_together': {('organization', 'year')},
            },
        ),
        migrations.CreateModel(
            name='RiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('risk_type', models.CharField(max_length=60)),
                ('impact_level', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('assessed_on', models.DateField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='core.organization')),
            ],
            options={
                'ordering': ['-assessed_on'],
                'indexes': [models.Index(fields=['organization', 'assessed_on'], name='governance__organiz_a625ad_idx'), models.Index(fields=['risk_type'], name='governance__risk_ty_af1564_idx')],
            },
        ),
    ]
