# Generated by Django 6.0.1 on 2026-01-27 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kras', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CriticalAttention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('task_area', models.CharField(max_length=50)),
                ('reason', models.TextField()),
                ('action', models.CharField(max_length=200)),
                ('is_resolved', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_attentions', to='core.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_attentions', to='core.organization')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'is_resolved'], name='people_crit_organiz_f20ad4_idx'), models.Index(fields=['task_area'], name='people_crit_task_ar_ddc26c_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(max_length=30)),
                ('effective_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='core.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_status_events', to='core.organization')),
            ],
            options={
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['organization', 'effective_date'], name='people_empl_organiz_70e229_idx'), models.Index(fields=['employee', 'effective_date'], name='people_empl_employe_44e5ca_idx')],
            },
        ),
        migrations.CreateModel(
            name='HiringGap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(max_length=100)),
                ('required', models.IntegerField(default=0)),
                ('current', models.IntegerField(default=0)),
                ('gap', models.IntegerField(default=0)),
                ('impact', models.CharField(max_length=20)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hiring_gaps', to='core.department')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_gaps', to='core.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hiring_gaps', to='projects.project')),
            ],
            options={
                'ordering': ['-gap'],
                'indexes': [models.Index(fields=['organization', 'impact'], name='people_hiri_organiz_358e51_idx'), models.Index(fields=['project'], name='people_hiri_project_f3fa8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeKRA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField()),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('target', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('achieved', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('achievement_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kras', to='core.employee')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_kras', to='core.organization')),
                ('kra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_kras', to='people.kra')),
            ],
            options={
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['organization', 'year', 'month'], name='people_empl_organiz_01710f_idx'), models.Index(fields=['employee', 'year', 'month'], name='people_empl_employe_939d57_idx')],
                'unique_together': {('employee', 'kra', 'year', 'month')},
            },
        ),
    ]
