# Generated by Django 6.0.1 on 2026-01-27 13:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('specialization', models.CharField(blank=True, max_length=200)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contractors', to='core.organization')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('planned_start', models.DateField()),
                ('planned_end', models.DateField()),
                ('actual_start', models.DateField(blank=True, null=True)),
                ('actual_end', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('delayed', 'Delayed')], default='not_started', max_length=20)),
                ('completion_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('contractor_score', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='construction.contractor')),
                ('phase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milestones', to='core.milestonephase')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'planned_start'],
            },
        ),
        migrations.CreateModel(
            name='DelayPenalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delay_days', models.IntegerField(default=0)),
                ('penalty_per_day', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('pending_recovery', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('critical_escalations', models.IntegerField(default=0)),
                ('escalation_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=20)),
                ('recorded_on', models.DateField()),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_penalties', to='construction.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_penalties', to='projects.project')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delay_penalties', to='construction.milestone')),
            ],
            options={
                'ordering': ['-recorded_on'],
            },
        ),
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('planned_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('actual_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('workers_present', models.IntegerField(default=0)),
                ('equipment_deployed', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='projects.project')),
            ],
            options={
                'ordering': ['date'],
                'indexes': [models.Index(fields=['date'], name='constructio_date_1f6dc6_idx')],
                'unique_together': {('project', 'date')},
            },
        ),
        migrations.CreateModel(
            name='DelayPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_version', models.CharField(default='v1.0', max_length=50)),
                ('predicted_delay_days', models.IntegerField(default=0)),
                ('model_confidence', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('weather_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('material_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contractor_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('financial_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('regulatory_risk', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('ai_insight_summary', models.TextField(blank=True)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('prediction_date', models.DateField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delay_predictions', to='projects.project')),
            ],
            options={
                'ordering': ['-prediction_date'],
                'indexes': [models.Index(fields=['prediction_date'], name='constructio_predict_74c8d1_idx')],
                'unique_together': {('project', 'prediction_date')},
            },
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['project', 'status'], name='constructio_project_bef69b_idx'),
        ),
        migrations.AddIndex(
            model_name='delaypenalty',
            index=models.Index(fields=['project', 'recorded_on'], name='constructio_project_e767f1_idx'),
        ),
        migrations.AddIndex(
            model_name='delaypenalty',
            index=models.Index(fields=['escalation_level'], name='constructio_escalat_81b46b_idx'),
        ),
    ]
